### ISSUE TITLE
can't subscribe to a certain feed

### ISSUE THREAD

**Issue by Aschonberger** [joshuacerdenia/NiceFeed#11]
I cant subscribe to http://stallman.org/rss/rss.xml, whenever i try subscribing through search results it tells me to do wnter the address manually, which doesnt work either.

**Comment by joshuacerdenia** [comment]
Hi, thanks for trying the app. Unfortunately I use an outside library for parsing RSS feeds so I can't fix this directly. In the future I may find a different library.
