### ISSUE TITLE
Add atom.xml support

### ISSUE THREAD

**Issue by budda85** [joshuacerdenia/NiceFeed#12]
Hey,
thanks for this app.
Can you add support for atom.xml?
I can add feeds like
[www.heise.de/rss/heise-atom.xml](www.heise.de/rss/heise-atom.xml) or
[www.heise.de/security/rss/news-atom.xml](www.heise.de/security/rss/news-atom.xml)
but there are still "No item found" showing in the feed.
This link
[www.heise.de/rss/heise.rdf](www.heise.de/rss/heise.rdf)
ist working well.
Thx

**Comment by joshuacerdenia** [comment]
Hi. Thanks for trying the app. Unfortunately I use an external library for parsing RSS feeds which currently does not support Atom. https://github.com/prof18/RSS-Parser

I may find a different library in the future.
