### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by bakinazik** [joshuacerdenia/NiceFeed#24]
Can't you make the dark theme work on android 9? I really love this app but if i can't use the dark mode it's gonna be really sad for me.

**Comment by joshuacerdenia** [comment]
Thanks for using the app :) I'm using the system-wide dark theme Android implemented in Android 10, so unfortunately Android 9 is not supported. This is not a priority right now, but I'm labeling this "help wanted" as you're not the first to ask.

**Comment by Ele-rigal** [comment]
Hey @joshuacerdenia ,
I took a look on the project and I found it interesting. Can I try to implement this feature with a pull request ?

**Comment by joshuacerdenia** [comment]
@Ele-rigal Yes, you are very welcome. :)

**Comment by joshuacerdenia** [comment]
Update forthcoming. Thanks @Ele-rigal for the PR!
