### ISSUE TITLE
Update all feeds in "New Entries" section

### ISSUE THREAD

**Issue by shumvgolove** [joshuacerdenia/NiceFeed#26]
Currently, selecting "New Entries" shows only feeds that was updated individually. Manually updating each and one of the feeds for new entries to appear is really painfull, so we should just update all feeds at once when selecting "New Entries" section.

**Comment by joshuacerdenia** [comment]
Thanks. This should be quick enough, will include it in the next update.

**Comment by joshuacerdenia** [comment]
Update rolled out.
