### ISSUE TITLE
Fails to bulid on F-Droid

### ISSUE THREAD

**Issue by jspricke** [joshuacerdenia/NiceFeed#28]
Hi,

the last release (v1.0.0-beta05.6) fails to build on F-Droid:
```
/home/vagrant/build/com.joshuacerdenia.android.nicefeed/app/build.gradle: Error: xpp3 defines classes that conflict with classes now provided by Android. Solutions include finding newer versions or alternative libraries that don't have the same problem (for example, for httpclient use HttpUrlConnection or okhttp instead), or repackaging the library using something like jarjar. [DuplicatePlatformClasses]
```
https://monitor.f-droid.org/builds/log/com.joshuacerdenia.android.nicefeed/16

Can you have a look?

**Comment by joshuacerdenia** [comment]
Thanks, will look into it.

**Comment by jspricke** [comment]
Just to let you know, 1.0.0-beta06 still fails with the same error.

**Comment by locness3** [comment]
This should be high-priority, there are currently no new updates for this app on F-Droid.

**Comment by locness3** [comment]
Looks like this is not a problem anymore?

**Comment by jspricke** [comment]
1.0.0-beta7 is there :).

**Comment by joshuacerdenia** [comment]
Yes. Thank you!
