### ISSUE TITLE
[Feature Request] Proxy Support

### ISSUE THREAD

**Issue by chromer030** [joshuacerdenia/NiceFeed#3]
Thanks for great and lovely app.
Please add Socks / HTTPS proxy support.

**Comment by joshuacerdenia** [comment]
I see that you closed this issue, but thank you for the comment anyway!

**Comment by chromer030** [comment]
Excuse me for closing issue by mistake , Please if it's possible add  ability to route traffic through proxy . eg Socks

**Comment by joshuacerdenia** [comment]
Thanks, I will look into it for a future update.

**Comment by joshuacerdenia** [comment]
Closing this as it's not a priority at the moment. May reconsider in the future.
