### ISSUE TITLE
Dark theme Not Working

### ISSUE THREAD

**Issue by chromer030** [joshuacerdenia/NiceFeed#4]
Hi , Dark theme doesn't work.
I restarted app after setting , cleared cache but issue persists.

![Screenshot_20200915-084815](https://user-images.githubusercontent.com/13361552/93912035-7fdadb00-fd03-11ea-896a-894ca6412a4f.png)

Android : 7.1.2 ViperOS
Arch : arm64
App version : latest ( Installed from Google Play )

**Comment by joshuacerdenia** [comment]
For now, Dark mode is supported on Android 10+ only. The latest update (which should be out in a few days) indicates this. Implementing full support is one of my priorities in the near future.
