### ISSUE TITLE
Alternative APK download?

### ISSUE THREAD

**Issue by IzzySoft** [joshuacerdenia/NiceFeed#7]
Great to see a good RSS feed reader without trackers! Would you mind making the APK available outside the (tracking) Play Store – for users outside that walled garden (e.g. those of Huawei devices)? You could attach it here [at Github releases](https://github.com/joshuacerdenia/NiceFeed/releases), for example, as many projects do. Thanks in advance!

Btw: looks like you accidentally included the APK of your other app (StarSearch) in the root of this repo :wink:

**Comment by joshuacerdenia** [comment]
Oops, that's embarrassing! Thanks for the comment and for trying the app. I made a new release as a middle version between the last update and the next, which includes an APK. Let me know if you run into any issues.

**Comment by IzzySoft** [comment]
Thanks a lot! As you asked for contributions, I went ahead and opened a PR with mine. Further, in about half an hour your app should become [available in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.joshuacerdenia.android.nicefeed) – users without Play Store will appreciate this (think of those Huawei users I've mentioned). As long as you keep tagging and attaching the APK, my updater should fetch new versions within 24h. If you want to link to it, you can [find a badge here](https://gitlab.com/IzzyOnDroid/repo/blob/master/README.md#what-are-the-requirements-an-app-must-meet-to-be-included-with-the-repo) which fits in snuggly into your ReadMe next to that of Google Play :wink:

**Comment by joshuacerdenia** [comment]
This is great, thank you!

**Comment by IzzySoft** [comment]
Gladly! As you've accepted my PR, I've set metadata here to follow that up (i.e. should you update the description, it will be pulled with the next release to be reflected with your app's listing in my repo). Should you add more things (like screenshots) to Fastlane, please let me know so I tell my updater to check those as well.

If you want to have your app on "F-Droid proper", you can [file a request for packaging](https://gitlab.com/fdroid/rfp/issues). Not hard to do, the "simple template" will suffice. Disclosure: I'm one of the F-Droid maintainers – actually the one dealing with getting RFPs ready for our packagers; so I would pick up from there and guide you through. Until then, it's of course fine just having your app in my repo – though trust is higher with "F-Droid proper", which then would always compile the APK from source once you tagged a release, so you cannot forget adding the APK :smile:

Thanks for your app and your help!

**Comment by joshuacerdenia** [comment]
I appreciate your interest in my app and your help!  My internet connection is impossible to work with right now due to maintenance, so I will be mostly gone for the next few days. After that, I'll get to look into all of this a little deeper. :) Thanks again!

**Comment by linsui** [comment]
Hi! Are you still interested in getting your app into F-Droid main repo? Since it's a pure kotlin app it would be pretty easy.

**Comment by joshuacerdenia** [comment]
Totally! Just been very busy lately and haven't paid much attention here. What do you suggest?

**Comment by linsui** [comment]
I'll prepare a MR on the F-Droid side. And @IzzySoft can review it. 😄

**Comment by linsui** [comment]
See https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8424

**Comment by fossdd** [comment]
@joshuacerdenia Can you put the donation link (https://www.paypal.com/paypalme/joshuacerdenia) in the README.md or as a [GitHub Funding Button](https://docs.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository)? That users can verify the link.

**Comment by linsui** [comment]
The link has been at the end of the readme.

**Comment by IzzySoft** [comment]
> And @IzzySoft can review it. :smile:

will do as soon as time permits. Busy day today. Ping me from the MR if should it go idle for 2 days without me showing up :wink:

**Comment by joshuacerdenia** [comment]
@linsui @IzzySoft Thank you both! Link is there in the README. :-)

**Comment by IzzySoft** [comment]
Review done. That network behavior is a bit strange. Repeated the test twice (uninstalling the app in between), same on the second run. Does it connect the first two search results automatically?

**Comment by joshuacerdenia** [comment]
Not sure I understand @IzzySoft , what do you mean?

**Comment by linsui** [comment]
See @IzzySoft 's review in https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8424

**Comment by IzzySoft** [comment]
Sorry @joshuacerdenia – I should have linked it. The review [is here](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8424#note_513793344). I was wondering about some network connections, especially one to Google's servers, when just performing a feed search where I'd only expect connections to Feedly.

**Comment by joshuacerdenia** [comment]
Thanks @IzzySoft, will look into it as soon as I can.

**Comment by joshuacerdenia** [comment]
Sorry for the lag @IzzySoft – I was digging into this, including the network connections the app is making, and not really seeing anything unexpected; so tbh, not sure what's going on. Any thoughts?

**Comment by IzzySoft** [comment]
Any pre-fetching being done? AndroidAuthority and AndroidPolice were the first two entries in the result list. AndroidAuthority uses GoogleTagManager, which might be resolving to the same `*.1e100.net` IP. AndroidPolice uses a ton of Google services. So that might explain in case you're pre-fetching.

**Comment by joshuacerdenia** [comment]
@IzzySoft No, though I have two background workers responsible for updating the feeds that run as soon as the app starts, depending on the settings and whether the work has already been scheduled. Would that explain it?

**Comment by IzzySoft** [comment]
With no feeds added yet? Well, let's blame the cache then: on the first round I had added AndroidAuthority, so it might have been that and cached somehow (though I especially uninstalled and reinstalled your app between the two rounds).

So: apologies for the trouble – and I've just merged the metadata. Next build cycle (most likely during this weekend) should pick it up if all goes well. Feel free to close this issue at your convenience (I just leave it open now in case you want to wait until your app really shows up at F-Droid).

Last question: Usually about 1..2 weeks after an app shows up at F-Droid.org I remove it from my repo – unless there's explicit demand to keep it (see [here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ) for some background). So please let me know in case you want NiceFeed to stay.

**Comment by joshuacerdenia** [comment]
Thank you for all your help @IzzySoft and sorry about that! Yes, please feel free to remove it from your repo when the time comes.
