### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [joshuacerdenia/NiceFeed#9]
there are several translation tools. 
[weblate](https://hosted.weblate.org/) 
[crowdin](https://crowdin.com/) 
[transifex](https://www.transifex.com/)
[bubu weblate](https://weblate.bubu1.eu/)

it would be easier than at github
I'm writing down my experiences here. But you have to decide what you want.
if you take value on opensource, you can use #weblate. otherwise i hang out a lot on #crowdin.
at #transifex it can be that you are rejected or that it takes a long time until you are accepted.

**Comment by joshuacerdenia** [comment]
Thanks for bringing this to my attention.

**Comment by mondlicht-und-sterne** [comment]
Since the issue dates back a long time - can you just close
the issue? Thank you, my initial Issie was also just information.
